### 1. Testar cadastro de cpf errado
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "Roberto",
    "email": "roberto@gmail.com",
    "senha": "abc",
    "cpf": "123456789",
    "endereco": "rua abc, 5",
    "celular": "47912345678"
}

### 2. Testar cadastro do ciclista
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "Roberto",
    "email": "roberto@gmail.com",
    "senha": "abc",
    "cpf": "12345678912",
    "endereco": "rua abc, 5",
    "celular": "47912345678"
}

### 3. Testar cadastro do ciclista
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "Marcos",
    "email": "marcos@gmail.com",
    "senha": "abc",
    "cpf": "12345678912",
    "endereco": "rua abc, 5",
    "celular": "47912345678"
}

### 4. Testar cadastro do ciclista
POST http://localhost:3000/ciclista
Content-Type: application/json

{
    "nome": "Ana",
    "email": "ana@gmail.com",
    "senha": "abc",
    "cpf": "12345678912",
    "endereco": "rua abc, 5",
    "celular": "47912345678"
}

### 5. Fazer Login do ciclista (Armazena o token automaticamente)
# @name loginReq
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "ana@gmail.com",
    "senha": "abc"
}

### 6. Consultar ciclista por ID (rota privada)
GET http://localhost:3000/ciclista/1
Authorization: {{loginReq.response.body.token}}

### 7. Consultar ciclista por nome (rota privada)
GET http://localhost:3000/ciclista/buscarNome/juan
Authorization: {{loginReq.response.body.token}}